/*
 * Created on 19/11/2011
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */

package com.antiaction.multithreading.datasource;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public class StatementWrapper implements Statement, Comparable {

	private static int keyInc = 1;

	protected long key;

	private boolean bClosed;

	private Statement stm;

	private ConnectionPooled connection;

	public StatementWrapper(Statement stm, ConnectionPooled connection) {
		this.stm = stm;
		this.connection = connection;
		synchronized (this.getClass()) {
			key = keyInc++;
		}
	}

	public int compareTo(Object o) {
		long dx = ((StatementWrapper)o).key - key;
		if ( dx > 0 ) {
			return 1;
		}
		else if ( dx < 0 ) {
			return -1;
		}
		else {
			return 0;
		}
	}

	public ResultSet executeQuery(String sql) throws SQLException {
		return stm.executeQuery( sql );
	}

	public int executeUpdate(String sql) throws SQLException {
		return stm.executeUpdate( sql );
	}

	public void close() throws SQLException {
		if ( !bClosed ) {
			stm.close();
			connection.closeStatement( this );
			stm = null;
			connection = null;
			bClosed = true;
		}
	}

	public int getMaxFieldSize() throws SQLException {
		return stm.getMaxFieldSize();
	}

	public void setMaxFieldSize(int max) throws SQLException {
		stm.setMaxFieldSize( max );
	}

	public int getMaxRows() throws SQLException {
		return stm.getMaxRows();
	}

	public void setMaxRows(int max) throws SQLException {
		stm.setMaxRows( max );
	}

	public void setEscapeProcessing(boolean enable) throws SQLException {
		stm.setEscapeProcessing( enable );
	}

	public int getQueryTimeout() throws SQLException {
		return stm.getQueryTimeout();
	}

	public void setQueryTimeout(int seconds) throws SQLException {
		stm.setQueryTimeout( seconds );
	}

	public void cancel() throws SQLException {
		stm.cancel();
	}

	public SQLWarning getWarnings() throws SQLException {
		return stm.getWarnings();
	}

	public void clearWarnings() throws SQLException {
		stm.clearWarnings();
	}

	public void setCursorName(String name) throws SQLException {
		stm.setCursorName( name );
	}

	public boolean execute(String sql) throws SQLException {
		return stm.execute( sql );
	}

	public ResultSet getResultSet() throws SQLException {
		return stm.getResultSet();
	}

	public int getUpdateCount() throws SQLException {
		return stm.getUpdateCount();
	}

	public boolean getMoreResults() throws SQLException {
		return stm.getMoreResults();
	}

	public void setFetchDirection(int direction) throws SQLException {
		stm.setFetchDirection( direction );
	}

	public int getFetchDirection() throws SQLException {
		return stm.getFetchDirection();
	}

	public void setFetchSize(int rows) throws SQLException {
		stm.setFetchSize( rows );
	}

	public int getFetchSize() throws SQLException {
		return stm.getFetchSize();
	}

	public int getResultSetConcurrency() throws SQLException {
		return stm.getResultSetConcurrency();
	}

	public int getResultSetType() throws SQLException {
		return stm.getResultSetType();
	}

	public void addBatch(String sql) throws SQLException {
		stm.addBatch( sql );
	}

	public void clearBatch() throws SQLException {
		stm.clearBatch();
	}

	public int[] executeBatch() throws SQLException {
		return stm.executeBatch();
	}

	public Connection getConnection() throws SQLException {
		return stm.getConnection();
	}

	public boolean getMoreResults(int current) throws SQLException {
		return stm.getMoreResults( current );
	}

	public ResultSet getGeneratedKeys() throws SQLException {
		return stm.getGeneratedKeys();
	}

	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return stm.executeUpdate( sql, autoGeneratedKeys );
	}

	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return stm.executeUpdate( sql, columnIndexes );
	}

	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return stm.executeUpdate( sql, columnNames );
	}

	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return stm.execute( sql, autoGeneratedKeys );
	}

	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return stm.execute( sql, columnIndexes );
	}

	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return stm.execute( sql, columnNames );
	}

	public int getResultSetHoldability() throws SQLException {
		return stm.getResultSetHoldability();
	}

}
